version: "3"
services:
  web:
    container_name: ${WEB_CONTAINER_NAME}
    # コンテナ内でgoコマンドを実行可能とするためにbuild:ではなくimage:を使用する
    image: golang:1.21.4-alpine3.18
    # build:
    #   context: ./src
    volumes:
      - ./src:/src
    ports:
      - ${WEB_PORT}:${WEB_CONTAINER_PORT}
    environment:
      - WEB_PORT=${WEB_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Asia/Tokyo
    depends_on:
      - db
    tty: true
    command: /bin/sh -c "cd /src && go mod tidy && apk update && apk add bash && tail -f /dev/null"

  db:
    container_name: ${POSTGRES_HOST}
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_CONTAINER_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Asia/Tokyo

volumes:
  postgres_data:
