version: "3"
services:
  web:
    image: golang:1.21.4
    volumes:
      - ./src:/app
    ports:
      - ${WEB_PORT}:${WEB_CONTAINER_PORT}
    environment:
      - TZ=Asia/Tokyo
    tty: true
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_CONTAINER_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Asia/Tokyo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
