name: Go

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Lint golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

      - name: Build
        run: go build -v ./...
