name: Go

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.4

      - name: Lint golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          working-directory: ./src

      - name: Build
        working-directory: ./src
        run: go build -v ./...

  deply:
    needs: build

    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GCP Authorization
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.0.1

      - name: Build and push to Cloud Build
        working-directory: ./src
        run: gcloud builds submit --suppress-logs --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.IMAGE_ID }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: gcloud beta run deploy ${{ secrets.CLOUD_RUN_SERVICE_ID }} --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.IMAGE_ID }}:${{ github.sha }}
